services:
  cli:
    build:
      context: .
    volumes:
      - ./:/var/app/www
    environment:
      PHEME_HOST: "${PHEME_HOST:-https://pheme.example.com/}"
      PHEME_API_KEY: "${PHEME_API_KEY:-}"
      PHEME_STATION_ID: "${PHEME_STATION_ID:-1}"
    command: composer test
